# Site settings
email: adrielmklein@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Adriel's Cycling Blog
description: A glimpse of life on the road
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Adriel Klein
profile_img: https://scontent-sjc2-1.xx.fbcdn.net/v/t1.0-9/13501673_10206762965772972_747059453831302189_n.jpg?oh=442c69e181ab0d278e92f4f7e360dc7e&oe=58883CC5
profile: sadklfjsaldfjsakdlf jskadfj salkdfj sakdlfj
social:
  github: http://github.com/adrielklein

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
